
unsigned long COUNTER = SYS_API__GET__LAST_OUTPUT_DATA_COUNTER_By_SLOT_INDEX(SLOT_INDEX, OUT_DEV__OUTPUT);
if(isCOUNTER != COUNTER){ isCOUNTER = COUNTER;

	//unsigned long TIME = SYS_API__GET__LAST_OUTPUT_DATA_TIME_By_SLOT_INDEX(SLOT_INDEX, OUT_DEV__OUTPUT);
	SYS_API__GET__LAST_OUTPUT_DATA_By_SLOT_INDEX(SLOT_INDEX, OUT_DEV__OUTPUT, SENSOR_message);

	if ( strlen(SENSOR_message) != 0 ){
		//printf("... ME_SOC(%ld)(%ld) %ld--> %s\n\r",TIME,COUNTER,OUT_DEV__OUTPUT,SENSOR_message);

		sprintf(SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.DATA[IN_DEV__INPUT],"%s",SENSOR_message);
		SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.DATA_STATUS[IN_DEV__INPUT] = 1;

		if(SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.PUSH[IN_DEV__INPUT]==1){
			pthread_mutex_lock(&SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.mutex);
			pthread_cond_signal(&SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.cond);
			pthread_mutex_unlock(&SLOT[IN_DEV__SLOT_INDEX].MEDIATOR.mutex);
		}
	}
}

