
int MySQL_START();

int MySQL_GET_PARAMETRES();
int MySQL_CREATE_DATABASE();
int MySQL_Connect();
int MySQL_Close();
int MySQL_READ_DEVICE();
int MySQL_READ_INPUT_OBJECTS();
int MySQL_READ_OUTPUT_OBJECTS();
int MySQL_READ_INTERCONN_OBJECTS();

int MySQL_CREATE_INTERCONN_OBJECTS(long DEVICE_1_ID, long OUTPUT_ID, long DEVICE_2_ID, long INPUT_ID);
int MySQL_CREATE_DEVICE_OBJECTS(long DEVICE_ID, char *DEVICE_DESCRIPTION, long DEVICE_TYPE, char *DEVICE_DATA, long DEVICE_ROOM);
int MySQL_CREATE_INPUT_OBJECTS(long DEVICE_ID, long INPUT_ID);
int MySQL_CREATE_OUTPUT_OBJECTS(long DEVICE_ID, long OUTPUT_ID);

int MySQL_DELETE_INTERCONN_OBJECTS(long DEVICE_1_ID, long OUTPUT_ID, long DEVICE_2_ID, long INPUT_ID);
int MySQL_DELETE_DEVICE_OBJECTS(long DEVICE_ID);
int MySQL_DELETE_INPUT_OBJECTS(long DEVICE_ID, long INPUT_ID);
int MySQL_DELETE_OUTPUT_OBJECTS(long DEVICE_ID, long OUTPUT_ID);

int MySQL_GET_IN_OR_OUT_OBJECT_DATA(char *IN_OR_OUT, long DEVICE_ID, long IN_OR_OUT_ID, char *DATA);
int MySQL_PUT_IN_OR_OUT_OBJECT_DATA(char *IN_OR_OUT, long DEVICE_ID, long IN_OR_OUT_ID, char *DATA);
int MySQL_PUT_DEVICE_OBJECT_DATA(long DEVICE_ID, char *DATA);
int MySQL_UPDATE_DEVICE_OBJECTS(long DEVICE_ID, long DEVICE_X, long DEVICE_Y, char *DEVICE_DESCRIPTION);
